### ISSUE TITLE
pyinfra should provide a way to encrypt sensible information

### ISSUE THREAD

**Issue by alexgarel** [Fizzadar/pyinfra#162]
Hi, first, thank you for pyinfra, I'm testing it on a small project, and so far, so good :-)

I didn't see anywhere in the doc, a recomandation regarding secrets.

In Ansible you would use vaults, and I think having secrets encoded thanks to a key is quite ok.

Shall I use my own specific library and ask for password using getpass in the begining of de deployment.py or even inventory ?

**Comment by alexgarel** [comment]
FYI, I think I'll use [privy](https://pypi.org/project/privy/).

**Comment by Fizzadar** [comment]
@alexgarel privy looks good! This is exactly the kind of thing perfectly suited to Python packages. I'd recommend loading up the secrets either in the inventory or group data files. 

I will add an example/pattern for this - can also swap out privy for hashicorp vault/aws secret manager/any python secret package :)

**Comment by Fizzadar** [comment]
I've now added an example @ https://github.com/Fizzadar/pyinfra/commit/59a4ee5284717b27a093c165277cc62bd7d0ddfd; struggling to get readthedocs to actually rebuild the docs but it's there!

**Comment by mcrot** [comment]
Hi @Fizzadar , thank you very much for this nice tool! I'm currently testing it for a small project which is deploying a web application.

I've seen your privy example in the docs, but I still don't understand the full picture how it can be used in a real application.
Can it be used to define a secret once in a similar as e.g. in Kubernetes and then to use it on the remote host?

For example, I need secrets on the remote machine, let's say a database password for the web application.
I've defined the password in clear text in the inventory as host data.
By using `files.template` a file `postgres.env` with environment variables is generated on the remote host.
Then I use `server.script` to start the application with `docker compose up`. The `docker-compose.yml` file contains a link to `postgres.env` with the password, so the containers of the database and of the web application can use it. 

At which level would `privy` be helpful in this scenario in order to improve the security and without entering the password all the time? Or am I on the wrong track with this whole idea?

**Comment by alexgarel** [comment]
@mcrot you use pivy to encrypt your secret in the repository where you store your infrastructure automation.
So when you run pyinfra, you input the password, it enables pyinfra to read your secrets, and write them down on the server (eg in your postgres.env).

This way you can even make your infrastructure automation repository public, as secrets are encrypted.

You can look at ansible vault for a similar concept (with more documentation online).
