### ISSUE TITLE
allow collection of users to be used in server.user()

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#212]
Should we allow there to be a collection of users in server.user() ?

Something like this:

```
server.user(
    {'Ensure users are removed'},
    ['kevin', 'bob'],
    present=False,
)
```

**Comment by Fizzadar** [comment]
So I was having a think about this - I think this is better written as:

```py
for user in ['kevin', 'bob']:
    server.user(
        {f'Ensure user {user} is removed'},
        user,
        present=False,
    )
```

My reasoning here is that the underlying command, `userdel`, only accepts one user at a time. Where pyinfra accepts lists (packages) this is because the underlying command allows multiple arguments.

That said, I think there's room for a new operation here, would explicitly cater for this user-case:

```py
@operation
def users(names, **user_kwargs):
    '''
    Add/remove/update multiple system users.

    + names: list of the usernames to manage
    + user_kwargs: dictionary of arguments to pass to ``server.user``

    Examples:

    .. code:: python

        # Delete multiple users
        server.users(
            {'Ensure kevin and bob users are removed'},
            ['kevin', 'bob'],
            present=False,
        )
    '''

    for name in names:
        user(name, **user_kwargs)

```

This also applies to `server.group` and `brew.tap`.

**Comment by mkinney** [comment]
I really like the first example.

Ok to close these issues unless you want to add the new operations.

**Comment by Fizzadar** [comment]
👍 sounds good; I think I'd rather not add operations as shortcuts for this kind of thing, a loop is more Pythonic :)

**Comment by mkinney** [comment]
Agree
