### ISSUE TITLE
Custom fact loading

### ISSUE THREAD

**Issue by wilypomegranate** [Fizzadar/pyinfra#296]
I stumbled on this project and it's everything I've been looking for to finally ditch ansible. :)

I was playing around with trying to load a custom fact that I wrote.

I imported it in my config.py hoping it'd be caught by the MetaClass for registering the Fact, but it seems that is_fact is called before the config is loaded in the cli main.

Is there another way to create a custom fact? I haven't been able to find a way.

**Comment by Fizzadar** [comment]
@wilypomegranate it looks like this was due to loading the config after parsing CLI arguments; a deploy works using a custom fact in `config.py` but `pyinfra fact X` does not. I've just pushed https://github.com/Fizzadar/pyinfra/commit/34e474c5d85f10f7f4b3f917e13a48fe9d5a5894 which fixes this, and will be part of the v0.14.5 release in the coming days.

**Comment by wilypomegranate** [comment]
Awesome! Thanks for the quick fix:)
