### ISSUE TITLE
@local don't use group_data variables 

### ISSUE THREAD

**Issue by nardusg** [Fizzadar/pyinfra#352]
Hi

So I am writing for a big group of servers, but just want to test @local . @local don't read group_data or is there something I need to do different ? Will this also happen for vagrent/virtualbox ?

Thanks

Nardus

**Comment by FooBarQuaxx** [comment]
@nardusg Not to be rude but those type of questions are not meant for the issue section of a project's repo. 
If you find something unclear/incomplete/bogus on the documentation, you can open an issue. 
I understand that some people want help and that's absolutely fine and that's why sites like stackoverflow are meant for. 
I've also noticed that some projects have blogs that those help questions can be submitted that others can respond/comment to.
This is my personal opinion.

**Comment by nardusg** [comment]
Jip, understand, that is why I ask it here, because I don't know where to ask it elsewhere. Is there a platform where I can ask questions ? Discord, IRC, telegram ?

**Comment by FooBarQuaxx** [comment]
I prefer that @Fizzadar decides on this.

**Comment by Fizzadar** [comment]
I agree that GitHub issues should be kept for bugs/documentation/etc issues rather than actual usage questions. I am investigating options for such discussions - to start I've created a reddit (https://www.reddit.com/r/pyinfra) which I am following/am more than happy to answer questions over.

 Also looking at other options, would be keen to avoid too many different places as it'll become hard to keep track. The reason I like something like reddit is conversations stick about a bit longer - problem with IRC/similar is things get lost very quickly.

**Comment by nardusg** [comment]
No, problem, thanks for creating it
