### ISSUE TITLE
If crontab exists but is empty, multiple `server.crontab` calls do not produce the correct results

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#524]
**Describe the bug**
If the crontab on the host is empty, multiple calls within a deploy will override each other, resulting in only the last call to `server.crontab` showing up in the crontab. Running the same deploy a second time works as expected, which I would assume means that an empty crontab is being treated differently than one that has one or more job definitions in it.

**To Reproduce**
- Empty crontab on host: `echo | crontab`
- Attempt to run a deploy that uses multiple calls to `server.crontab`

**Expected behavior**
I would expect the crontab to have all of the jobs from all of the `server.crontab` calls.

**Meta**
+ Include output of `pyinfra --support`.
```
❯ pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Darwin
      Platform: macOS-10.14.6-x86_64-i386-64bit
      Release: 18.7.0
      Machine: x86_64
    pyinfra: v1.3.5
    Executable: /Users/----/.virtualenvs/05-hz-pyinfra-d0Faa_8y-py3.9/bin/pyinfra
    Python: 3.9.1 (CPython, Clang 10.0.1 (clang-1001.0.46.4))
```
+ How was pyinfra installed (source/pip)? Virtualenv via `poetry`

**Comment by Fizzadar** [comment]
Nice spot @taranlu-houzz! This is due to the two phase fact gathering before operation execution. Fixed by updating the fact during operation "prep" (https://github.com/Fizzadar/pyinfra/commit/9ab5dac6c250ab022e8875eac89b03e6d8cd4a7b). There is a wider issue here to test for this correct behaviour as well: https://github.com/Fizzadar/pyinfra/issues/470.

Fix is now released in `v1.3.6` :)
