### ISSUE TITLE
Add support for openbsd's doas

### ISSUE THREAD

**Issue by hazayan** [Fizzadar/pyinfra#585]
Openbsd phased out the use of `sudo` for privilege escalation for a while now and replaced with its own `doas`. It would be nice to have support added for `doas` to avoid directly connecting with root in order to perform tasks that require super user privileges.

**Comment by Fizzadar** [comment]
👍 keen to get this implemented!

**Comment by hendursaga** [comment]
I doubt there are very many if any differences, but supporting FreeBSD's port of doas would be great as well!

**Comment by yggdr** [comment]
This might be the right point to also start supporting Solaris'/Illumos' `pfexec`, and maybe unify the interface of using them? Instead of having various `use_<UTIL>_login`, `use_<UTIL>_password`, `preserve_<UTIL>_env`, remove the specific name, and provide a new parameter like e.g. `priv_tool` that can be set to one of the supported methods. Then I could write in my deploys `files.file(..., priv_tool=doas, use_priv_login=True)`.

This way, when I adapt the deploy to another OS, or simply when I have to switch to sudo because I started to need to use some of its features, I only have change it at one point. That point could even be somewhere central, instead of in every single operation.

**Comment by Fizzadar** [comment]
This has now been released in v1.5.
