### ISSUE TITLE
Inventory groups renamed to .lower()

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#66]
Why are the groups specified in the inventory renamed to their lowercase counterpart ? I find this confusing for beginners.

**Comment by Fizzadar** [comment]
This was originally in place because an inventory was kind-of-like a constant - however I no longer think this makes sense (dynamic inventories, `--limit`). I don't think there should be restrictions on either inventory being all caps or group data being all lower.

Currently if an inventory file imports or defines a variable in all caps that isn't the right type the inventory setup will fail (https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/cli.py#L501). The group data check is significantly more robust (https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/cli.py#L578).

Current plans:

+ Remove `islower()` check on group data
+ Remove `isupper()` check on inventory groups and instead check variables to be a list/tuple of strings/tuples, which is the correct data structure
+ Recommend that, to avoid polluting group data, any dynamic data is loaded inside function calls (functions are not valid group data and ignored)
+ Recommend the same technique for generating dynamic inventories (although the list of strings/tuples validation will prevent polluting the inventory somewhat)

This will enable inventory groups and group data in lowercase or capitals, as the user pleases (lowercase preferred, keeping all caps vars for constants). Additionally it's backwards compatible without breaking inventories that define extra lowercase variables.

**Comment by Fizzadar** [comment]
As a result of the above changes, defining a group+data in one tuple will no longer be valid - this was an undocumented API-style feature that should never have been allowed in the CLI to begin with (the API takes kwargs where group=list-of-hosts or tuple of `(list-of-hosts, data)`).

**Comment by hoh** [comment]
Good to read.

I was also thinking about this line that converts the inventory names to lower():
https://github.com/Fizzadar/pyinfra/blob/3e29653402fd8847591e18fc4fdf307ce2d23f4d/pyinfra/api/inventory.py#L69

**Comment by Fizzadar** [comment]
@hoh yep, I'll be removing that entirely :)!

**Comment by Fizzadar** [comment]
This is now complete @ https://github.com/Fizzadar/pyinfra/commit/4ff751dc17561ac94c7d8b16938fa8649c997286, due for release as `v0.2` in the next few days.
