### ISSUE TITLE
Setup cwd to be in the path when executing the CLI

### ISSUE THREAD

**Issue by judofyr** [Fizzadar/pyinfra#71]
I've written some modules for managing Postgres databases/users and decided to move them out into their own directory. However, the following doesn't work:

```python
from modules import postgres
```

This is because `sys.path` doesn't contain the directory. Is this intentional?

**Comment by Fizzadar** [comment]
@judofyr it should be imported from `pyinfra.modules` assuming they're located at `pyinfra/modules/postgres.py` (and facts at `pyinfra/facts/postgres.py`)?

Currently there's no "extension" module support, which is something I need to define and come up with a methodology for, see: #12

**Comment by judofyr** [comment]
I don't have my own fork of pyinfra, no. I'm not sure how much "extension" module support you actually need? I just import `pyinfra.api` in my (local) module and use the `@operation`-decorator. Everything seems to work nicely (after I add `.` to `sys.path`).

**Comment by Fizzadar** [comment]
@judofyr the extension stuff is a plan for creating extra modules that eventually get rolled into pyinfra itself. Your issue is to do with the Python module system rather than pyinfra itself - what does your directory layout look like and how/where are you executing the code?

**Comment by judofyr** [comment]
At the moment it looks like this:

```
├── README.md
├── deploy.py
├── files
│   ├── ....
├── group_data
│   └── all.py
├── inventories
│   └── production.py
├── modules
│   ├── __init__.py
│   └── postgres.py
```

But I must add `sys.path.append(".")` to deploy.py in order for `from modules import postgres` to work.

**Comment by hoh** [comment]
@judofyr you can also use the [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) environment variable to let Python know it can import modules from that directory. It is cleaner that hardcoding`sys.path.append(...)`.

Opening a Pull Request for integrating the postgres module into pyinfra would also be useful to many users.

**Comment by Fizzadar** [comment]
@judofyr this is because the deploy file is imported using [`load_source`](https://docs.python.org/2/library/imp.html#imp.load_source) - meaning any imports are executed from the same directory as the pyinfra util file (`/var/lib/Python2.7/site-packages/pyinfra/api/util.py` or similar).

There are two ways to "fix" this:

1. As @hoh said - simply run pyinfra with `PYTHONPATH=. pyinfra...` envar set before
2. Install your modules package as a Python package, such that it's importable anywhere

The best way to handle this would be creating actual pyinfra modules/facts for postgres. The problem is more a Python path issue than pyinfra itself - I'm not too keen on pyinfra fiddling with `sys.path`..

**Comment by judofyr** [comment]
Well, if I run `python deploy.py`, then the cwd *would* be a part of the `sys.path`. I think it would be more consistent if `python deploy.py` and `pyinfra deploy.py` ends up executing with the same `sys.path`.

**Comment by Fizzadar** [comment]
@judofyr I think that makes sense :)

**Comment by Fizzadar** [comment]
@judofyr this should now be fixed @ https://github.com/Fizzadar/pyinfra/commit/92e1467be925294ec907602db7ee4c79662e1990 :)
