### ISSUE TITLE
Allow specifying an alternative ~/.ssh/config file

### ISSUE THREAD

**Issue by artizirk** [Fizzadar/pyinfra#715]
That would allow shipping the `ssh_config` file in the repo next to other inventory and deploy files.
I mostly use the `ssh_config` file for configuring ProxyJump config arguments.

OpenSSH client has [`-F` option](https://man.openbsd.org/ssh#F) that allows using other config file.

Currently i'm hacking around this limitation by injecting this snippet into my `config.py`

```
from os import path
from pyinfra.api.connectors.sshuserclient import client
from pyinfra.api.connectors.sshuserclient.config import SSHConfig
from pyinfra.api.util import memoize

@memoize
def get_ssh_config():
    user_config_file = 'ssh_config'
    if path.exists(user_config_file):
        with open(user_config_file) as f:
            ssh_config = SSHConfig()
            ssh_config.parse(f)
            return ssh_config

client.get_ssh_config = get_ssh_config
```

**Comment by Fizzadar** [comment]
Great idea! I've added an implementation of this in https://github.com/Fizzadar/pyinfra/pull/734/commits/7bdf55db6e5e94f7b3d87cbf0094ddc5646304f8, pending 1.5.1 or 1.6.

**Comment by Fizzadar** [comment]
This is now live in `v1.6` :)

**Comment by themanifold** [comment]
Just wanted to make it clear that what you do to set this is, for example, in `group_data/all.py`, add `ssh_config_file = "custom_ssh_config"`. If you wanted to set a custom config per group, then you would put that into an appropriate `group_data/some_group.py`.

Writing this because there are no docs apart from this line of code: https://github.com/Fizzadar/pyinfra/blob/7bdf55db6e5e94f7b3d87cbf0094ddc5646304f8/pyinfra/api/connectors/ssh.py#L170
