### ISSUE TITLE
Files/Link force=True can still fail with 'File exists'

### ISSUE THREAD

**Issue by drewp** [Fizzadar/pyinfra#719]
My code:
```
    files.link(path='/etc/resolv.conf', target='/run/systemd/resolve/resolv.conf', force=True)
```

Output:
```
--> Preparing operations...
    Loading: net.py
    Loaded fact link (path=/etc/resolv.conf)
...
    [garage] Ready: net.py

--> Proposed changes:
    Groups: inventory / pi
    [garage]   Operations: 8   Commands: 10   

--> Beginning operation run...
--> Starting operation: Files/Link (path=/etc/resolv.conf, target=/run/systemd/resolve/resolv.conf, force=True)
    [garage] ln: failed to create symbolic link '/etc/resolv.conf': File exists
    [garage] Error
```

I did not expect `ln` to be able to error, since force=True should have rm'd the file first. (I also expected pyinfra to use `ln -sf` instead of `rm`-then-`ln`, but whatever.)

Here are some commands I ran on the remote host:
```
pi@garage:~ $ test -L /etc/resolv.conf
pi@garage:~ $ echo $?
1

pi@garage:~ $ stat -c 'user=%U group=%G mode=%A atime=%X mtime=%Y ctime=%Z size=%s %N' /etc/resolv.conf
user=root group=root mode=-rw-r--r-- atime=1620399617 mtime=1639380484 ctime=1639380484 size=115 '/etc/resolv.conf'
```

+ How was pyinfra installed (source/pip)? virtualenv + pip

```
% env/bin/pyinfra --support
--> Support information:

    System: Linux
      Platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.33
      Release: 5.11.0-40-generic
      Machine: x86_64
    pyinfra: v1.5
    Executable: env/bin/pyinfra
    Python: 3.9.9 (CPython, GCC 10.3.0)
```

**Comment by Fizzadar** [comment]
Hi @drewp thank you for reporting this; it should now be resolved in `v1.6.1` by https://github.com/Fizzadar/pyinfra/commit/6c1af9f0cde47544658f3f1f559a032f5ee3f579 + https://github.com/Fizzadar/pyinfra/commit/39c604b5a24afd4cb79c0884f6011629a178c1bc.

Essentially the `files.Link` fact was returning `null` incorrectly when it should return `false` (indicating the path exists but isn't a link). The fact update means this works as expected.

Regarding the `ln -sf` - the `rm` part is executed outside of the link function itself (it's the same code for `files.directory` & `files.file` operations) which is why rewriting the link isn't used.
