### ISSUE TITLE
Poetry installs old version of PyInfra

### ISSUE THREAD

**Issue by mjmare** [Fizzadar/pyinfra#744]
When I use poetry to manage dependencies like pyinfra it finds an old (?) version 1.14.14, instead of the most recent one 1.6.1.
```
poetry add -D pyinfra
Using version ^1.14.14 for pyinfra
```
Don't know if it is something you can do something about it. 
As a workaround I now fix the version:
```
poetry add -D pyinfra==1.6.1
```

**Comment by Fizzadar** [comment]
This appears to be because poetry does not support yanked releases, there’s an issue tracking that here: https://github.com/python-poetry/poetry/issues/2453.

Another workaround would be specifying any version except the yanked one with `pyinfra!=1.14.14`. Closing this as its upstream and the pip implementation is over 2 years old so it’s not a new thing!

**Comment by mjmare** [comment]
Thanks for investigating. 
pyinfra!=1.14.14 is a better workaround than fixing it to the current version. Thanks for the suggestion. 
Great, now I can use the --data option.
