### ISSUE TITLE
CI fails on Alpine docker - FileNotFoundError: [Errno 2] No such file or directory: 'ssh'

### ISSUE THREAD

**Issue by melezhik** [Fizzadar/pyinfra#908]
## Describe the bug

unit tests fail in Apine docker instance with an error - “ FileNotFoundError: [Errno 2] No such file or directory: 'ssh'”

In absence of ssh setup , should ssh tests be optional ? 

## To Reproduce

Run SparrowCI. 

See error report - https://ci.sparrowhub.io/report/1507

## Expected behavior

Unit tests should pass.

## Meta

 See details in https://ci.sparrowhub.io/report/1507

**Comment by Fizzadar** [comment]
This appears to be an issue because the SSH config test uses the `ssh` command in the proxy config, I've switched this to `echo` in https://github.com/Fizzadar/pyinfra/commit/e3fee1d846177eca27484ddc4b4c095051790e14.

Also worth noting I don't think counts as a bug - the CI/tests are officially supported on GitHub CI only.

**Comment by melezhik** [comment]
> Also worth noting I don't think counts as a bug - the CI/tests are officially supported on GitHub CI only.

Sorry, I don’t get that. you just said this is a bug 😊, bugs appear in a code not in systems that reveal bugs
