### ISSUE TITLE
How to run a task in background ?

### ISSUE THREAD

**Issue by julienfr112** [Fizzadar/pyinfra#947]
At the end of the task, I want to run a python script in background but return immediately. (it's for cache purpose, so i don't want to wait for it to finish, if that fail or so, it's not that important)

I've tried 
- using server. shell([nohup mycommand &"])
 - do a double fork in the command itsef
 
But not to prevail : server.shell wait for my command to complete, even forked or detached.

Any ideas ?

PS : I'm REALLY happy with pyinfra, amazing tech guys !!

**Comment by handcraftedcomputers** [comment]
It looks like the remote sshd is waiting on the output of mycommand, so doesn't complete until stdout/stderr is closed by the subprocess exiting (replicated here using "sleep").  Try:

```
server.shell(['nohup mycommand > /dev/null 2>&1 &'])
```

**Comment by hjoukl** [comment]
For anyone stumbling upon this like me, looking for info on how to start a long running process through `server.shell`: 

The essential part is that stdout/stderr need to be redirected to `/dev/null` to allow for ssh returning. `nohup` may or may not be necessary depending on the shell/env setup in place, but safer to use anyway, to be independent of such setup.

If you also need to e.g. change to a certain directory before running your command you might need to jump through some additional hoops:

```
# Actual command simulated with sleep, srv is the target server:
#
#          Combine cd and actual sleep command                     
#                          |
#          vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# ssh srv "{ cd /tmp && (nohup sleep 10 &); } >/dev/null 2>&1 &"
#                       ^^^^^^^^^^^^^^^^^^    ^^^^^^^^^^^^^^^^^
#                                |                    |
#                       Run actual command    Redirect all output
#                       as subprocess in      and run in background
#                       background, to        to allow ssh to
#                       detach from combined  return.
#                       parent command.
#                       Essentially a
#                       double fork.
```

The "subprocess in background" bit avoids leaving an additional `sh -c { cd /tmp && ... }` parent process on the target server.

Of course, you might be better off to stuff this complexity into a startup script for your command. Or make it a proper `systemd` service in the first place. ;-)

EDIT:
In pyinfra terms, the above ssh example would be:

```python
server.shell(["{ cd /tmp && (nohup sleep 10 &); } >/dev/null 2>&1 &"])
```

I just realized there's also a global `_chdir` parameter (https://docs.pyinfra.com/en/2.x/arguments.html#shell-control-features) to switch directory before executing the command. However, this simply adds `cd ... && ` before the given command string, which makes it unusable here imho, since all output must be redirected/detached from stdout/stderr.

Might be useful to change this to adapt for such use case, maybe in combination with a `_nohup` option(?).
